name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
