name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Run tests
        run: xcodebuild
          -project NASAClient.xcodeproj
          -scheme NASAClient
          -destination 'platform=iOS Simulator,name=iPhone 15'
          clean test
