name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Inject API key
        run: echo "let API_KEY = \"${{ secrets.API_KEY }}\"" > ./NASAClient/API/Secret.swift
      - name: Build
        run: xcodebuild 
          -scheme NASAClient
          -sdk iphonesimulator
          -configuration Debug
          build
      - name: Run tests
        run: xcodebuild
          -scheme NASAClient
          -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 12'
          clean test
